### ISSUE TITLE
TokenData rotation "NaN" is not a number between 0 and 360

### ISSUE THREAD

**Issue by Calz00ne** [brunocalado/ouija-board-for-sequencer#1]
Use of macro results in audio playing, but no animation or movement of actor and displays error "TokenData rotation "NaN" is not a number between 0 and 360". The more spaces it would have moves results in more error codes, about 30 errors per letter.

**Comment by brunocalado** [comment]
yeap

Use the macro from Sequencer module. The dev fixed. Just go to sequencer compendium and search for ouija there.

I'll fix this one for v10 only soon.

**Comment by brunocalado** [comment]
> t no animation or movement of actor and displays error "TokenData rotation "NaN" is not a number between 0 and 360". The more spaces it would have moves results in more error codes,

I think I fixed this with the new release. But, it's v10 only.
